const mongoose = require("mongoose");
const Hospital = require("../models/Hospital.js");

main();

async function main() {
  try {
    await mongoose.connect("mongodb://127.0.0.1:27017/LifeLine");
    console.log("✅ MongoDB Connected");
  }
  catch(error){
    console.log("Database not connected");
  }
}

// Optional: clear previous hospitals
await Hospital.deleteMany({});
console.log("🧹 Old hospital data cleared");

// Insert hospitals
await Hospital.insertMany([
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1001",
    name: "Sanjeevani MultiCare Hospital",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "Multi-specialty",
    ownership: "Private",
    licence: "LIC-2025-MP-01",
    accreditation: "NABH",
    accCertificates: ["ISO9001", "QualityCare2024"],
    emgServices: "24x7 Emergency with ICU and Trauma Center",
    address: "Sector 5, Arera Colony",
    landmark: "Near DB Mall",
    cityOrVillage: "Bhopal",
    pincode: "462016",
    district: "Bhopal",
    state: "Madhya Pradesh",
    coordinates: { latitude: 23.2599, longitude: 77.4126 },
    image: "hospital1.jpg",
    phoneNo1: "9876543210",
    phoneNo2: "9753124680",
    email: "info@sanjeevani-mc.in",
    totalEmp: 250,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        rating: 5,
        comment: "Excellent facilities and staff.",
      },
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1002",
    name: "LifeCare General Hospital",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "General",
    ownership: "Trust",
    licence: "LIC-2025-UP-02",
    accreditation: "ISO",
    accCertificates: ["QualityFirst2023"],
    emgServices: "Ambulance and emergency wards available 24x7",
    address: "Civil Lines",
    landmark: "Opposite Collector Office",
    cityOrVillage: "Prayagraj",
    pincode: "211001",
    district: "Prayagraj",
    state: "Uttar Pradesh",
    coordinates: { latitude: 25.4358, longitude: 81.8463 },
    image: "hospital2.jpg",
    phoneNo1: "9898989898",
    email: "lifecare@hospital.org",
    totalEmp: 180,
    reviews: [
      {
        userId: new mongoose.Types.ObjectId(),
        rating: 4,
        comment: "Good for general treatments.",
      },
    ],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1003",
    name: "Aarogya Super-specialty Center",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "Super-specialty",
    ownership: "Private",
    licence: "LIC-2025-RJ-03",
    accreditation: "JCI",
    accCertificates: ["CardiacExcellence2025"],
    emgServices: "Advanced heart and neuro emergency care",
    address: "Tonk Road",
    landmark: "Opp. Metro Station",
    cityOrVillage: "Jaipur",
    pincode: "302015",
    district: "Jaipur",
    state: "Rajasthan",
    coordinates: { latitude: 26.9124, longitude: 75.7873 },
    image: "hospital3.jpg",
    phoneNo1: "9123456780",
    email: "contact@aarogya-specialty.in",
    totalEmp: 320,
    reviews: [],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1004",
    name: "Niramaya Clinic",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "Clinic",
    ownership: "Individual",
    licence: "LIC-2025-UP-04",
    accreditation: "ISO",
    accCertificates: [],
    emgServices: "Basic first aid and emergency consultation",
    address: "Mahatma Gandhi Marg",
    landmark: "Near Railway Station",
    cityOrVillage: "Lucknow",
    pincode: "226001",
    district: "Lucknow",
    state: "Uttar Pradesh",
    coordinates: { latitude: 26.8467, longitude: 80.9462 },
    image: "hospital4.jpg",
    phoneNo1: "9456781230",
    phoneNo2: "9988776655",
    email: "niramaya.clinic@gmail.com",
    totalEmp: 25,
    reviews: [],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1005",
    name: "Sai MultiCare Hospital",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "Multi-specialty",
    ownership: "Private",
    licence: "LIC-2025-MH-05",
    accreditation: "NABH",
    accCertificates: ["ISO14001"],
    emgServices: "24x7 with emergency dialysis and burns unit",
    address: "Andheri West",
    landmark: "Near Infinity Mall",
    cityOrVillage: "Mumbai",
    pincode: "400053",
    district: "Mumbai",
    state: "Maharashtra",
    coordinates: { latitude: 19.076, longitude: 72.8777 },
    image: "hospital5.jpg",
    phoneNo1: "9876543201",
    phoneNo2: "9765432109",
    email: "info@saimulticare.in",
    totalEmp: 400,
    reviews: [],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1006",
    name: "Metro City General Hospital",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "General",
    ownership: "Government",
    licence: "LIC-2025-DL-06",
    accreditation: "NABH",
    accCertificates: ["GovtHealthStandard2024"],
    emgServices: "Emergency and outpatient services 24x7",
    address: "Dwarka Sector 12",
    landmark: "Metro Gate 2",
    cityOrVillage: "Delhi",
    pincode: "110075",
    district: "New Delhi",
    state: "Delhi",
    coordinates: { latitude: 28.6139, longitude: 77.209 },
    image: "hospital6.jpg",
    phoneNo1: "9312345678",
    email: "metrocity@health.gov.in",
    totalEmp: 600,
    reviews: [],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1007",
    name: "Swasthya Clinic and Lab",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "Clinic",
    ownership: "Partnership",
    licence: "LIC-2025-MP-07",
    accreditation: "ISO",
    accCertificates: [],
    emgServices: "OPD and diagnostic lab available",
    address: "Nehru Nagar",
    landmark: "Behind Bus Depot",
    cityOrVillage: "Indore",
    pincode: "452001",
    district: "Indore",
    state: "Madhya Pradesh",
    coordinates: { latitude: 22.7196, longitude: 75.8577 },
    image: "hospital7.jpg",
    phoneNo1: "9898981212",
    phoneNo2: "9876501234",
    email: "contact@swasthya.in",
    totalEmp: 45,
    reviews: [],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1008",
    name: "CarePlus Super-specialty Hospital",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "Super-specialty",
    ownership: "Private",
    licence: "LIC-2025-UP-08",
    accreditation: "NABH",
    accCertificates: ["NeuroCare2024"],
    emgServices: "ICU and Cardiac Emergency Unit 24x7",
    address: "Gomti Nagar",
    landmark: "Near Fun Mall",
    cityOrVillage: "Lucknow",
    pincode: "226010",
    district: "Lucknow",
    state: "Uttar Pradesh",
    coordinates: { latitude: 26.8505, longitude: 80.949 },
    image: "hospital8.jpg",
    phoneNo1: "9123456123",
    email: "careplus@hospital.in",
    totalEmp: 520,
    reviews: [],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1009",
    name: "Asha General Hospital",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "General",
    ownership: "Private",
    licence: "LIC-2025-RJ-09",
    accreditation: "ISO",
    accCertificates: [],
    emgServices: "24x7 emergency ward and pharmacy",
    address: "M.I. Road",
    landmark: "Near Raj Mandir",
    cityOrVillage: "Jaipur",
    pincode: "302001",
    district: "Jaipur",
    state: "Rajasthan",
    coordinates: { latitude: 26.9157, longitude: 75.8189 },
    image: "hospital9.jpg",
    phoneNo1: "9834567812",
    email: "asha@hospital.org",
    totalEmp: 210,
    reviews: [],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    hospitalID: "HSP1010",
    name: "Divine Heart MultiCare Hospital",
    hospitalHeadID: new mongoose.Types.ObjectId(),
    type: "Multi-specialty",
    ownership: "Private",
    licence: "LIC-2025-UP-10",
    accreditation: "JCI",
    accCertificates: ["ISO9001", "Cardio2025"],
    emgServices: "24x7 Cardiology and Emergency services",
    address: "Civil Lines",
    landmark: "Opp. Bus Stand",
    cityOrVillage: "Varanasi",
    pincode: "221002",
    district: "Varanasi",
    state: "Uttar Pradesh",
    coordinates: { latitude: 25.3176, longitude: 82.9739 },
    image: "hospital10.jpg",
    phoneNo1: "9812345678",
    phoneNo2: "9765432100",
    email: "divineheart@multicare.in",
    totalEmp: 300,
    reviews: [],
  },
]);

hospital.save()
.then((res)=>{
    console.log(res);
}).then((err)=>{
    console.log(err);
});
